# Generated by Django 4.2.6 on 2026-03-25 01:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpaPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CpaSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpaQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('question', tinymce.models.HTMLField()),
                ('answer', tinymce.models.HTMLField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpa.cpapaper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpa.cpasubject')),
            ],
        ),
        migrations.AddField(
            model_name='cpapaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpa.cpasubject'),
        ),
    ]
