# Generated by Django 4.2.6 on 2026-05-11 18:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cpa', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('slug', models.SlugField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentImage', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='cpa.posts')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
