# Generated by Django 4.2.6 on 2026-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpa', '0003_posts_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
