# Generated by Django 4.2.6 on 2026-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpa', '0004_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
