# Generated by Django 4.2.6 on 2025-08-06 20:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('text', tinymce.models.HTMLField()),
                ('question_num', models.IntegerField()),
                ('opt_1', models.CharField(blank=True, max_length=500, null=True)),
                ('opt_2', models.CharField(blank=True, max_length=500, null=True)),
                ('opt_3', models.CharField(blank=True, max_length=500, null=True)),
                ('opt_4', models.CharField(blank=True, max_length=500, null=True)),
                ('right_opt', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.IntegerField(blank=True, choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3'), (3, 'Option 4')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questionimages/')),
                ('explanation', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'subject', 'question_num'],
            },
        ),
    ]
