# Generated by Django 4.2.6 on 2025-08-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Paper 1'), (2, 'Paper 2'), (3, 'Paper 3')], null=True),
        ),
    ]
