# Generated by Django 4.2.6 on 2025-08-22 16:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasneb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('text', tinymce.models.HTMLField()),
                ('ans', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
