# Generated by Django 4.2.6 on 2025-08-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_subject_alter_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_opt',
        ),
    ]
