# Generated by Django 4.2.6 on 2025-09-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_course_subject_mysubjects_mycourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
