# Generated by Django 4.2.6 on 2025-09-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
