# Generated by Django 4.2.6 on 2025-09-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
