# Generated by Django 4.2.6 on 2025-10-21 18:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_book_availability_book_price_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
