# Generated by Django 4.2.6 on 2026-02-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMFProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MMFMonthlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Average monthly yield (%)', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rates', to='questions.mmfprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='questions_m_provide_2bbbc4_idx')],
                'unique_together': {('provider', 'year', 'month')},
            },
        ),
    ]
