# Generated by Django 4.2.6 on 2026-03-23 00:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_mmfprovider_mmfmonthlyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('question', tinymce.models.HTMLField()),
                ('answer', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
