# Generated by Django 4.2.6 on 2026-03-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_cpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpa',
        ),
    ]
