# Generated by Django 4.2.6 on 2026-05-04 23:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_mynotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adinfo',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
