# Generated by Django 4.2.6 on 2026-05-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_sfprovider_sfmonthlyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfmonthlyrate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfmonthly_rates', to='questions.sfprovider'),
        ),
    ]
